### ISSUE TITLE
Lora17層の場合のパターン対応

### ISSUE THREAD

**Issue by toretate** [Zuntan03/LoraBlockWeightPlotHelper#2]
一般のLora (Loconじゃないやつ)の場合、SuperMager では パラメータ17個だけが使われ、残りのパラメータは無視されます
無視層：IN00、IN03、IN09、IN10、IN11、OUT00、OUT01、OUT02

下記が 17層を出すセル数式なので、これを PlotHelper のどこかに入れておいて貰えないでしょうか？
```
=B8&":"&JOIN(",",E8:F8)&","&JOIN(",",H8:L8)&","&JOIN(",",P8)&","&JOIN(",",T8:AB8)
```

----
## 理由１

SuperMager の Loraマージでは、Loconでは無い場合パラメータの先頭から順に下記層にマッピングされます
Base, IN01, IN02, IN04, IN05, IN06, IN07, IN08, MID, OUT03, OUT04, OUT05, OUT06, OUT07, OUT08, OUT09, OUT10, OUT11
＊それ以降は利用されません

なので、PlotHelper の AC8 セルに出力された形式を SuperMarger で使うと、渡されたデータ先が意図してないところに設定されます
例：IN00を変更していると思ってたが、実際にはIN01を変更している

##  理由２
LoraBlockWeight に 26層のパラメータを渡した場合と、17層のパラメータを渡した場合とで結果が変わってくるようです。
一般Loraでのパラメータ調整には、17層用の出力が必要です
（無視される IN00, IN03, IN09, IN10, IN11, OUT00,OUT01, OUT02 をそれぞれ 0 や 1 で埋めても、SuperMager に 17層を渡した結果
と一致しない）

**Comment by Zuntan03** [comment]
ありがとうございます。
ご提案のセルを出力欄の下に追加しました。
スプレッドシートをコピーし直すと更新が適用されます。
https://docs.google.com/spreadsheets/d/1RPjlQOFt8KtNVhigmZB5LV_p-omnxj5LPPB1boYShvg/copy

**Comment by toretate** [comment]
@Zuntan03 
ありがとうございます！
